hello:
	mkdir -p bin
	g++ -g Prime_Numbers.cpp -o bin/prime_numbers
other:
	mkdir -p bin
	g++ -g others_answer.cpp -o bin/others_answer
compare:
	mkdir -p bin
	g++ -g compare.cpp -o bin/compare
clean:
	rm -rf bin