mkbin:
	mkdir -p bin
code1:	mkbin
	g++ code1.cpp -o bin/code1
multiset: mkbin
	g++ study_multiset.cpp -o bin/multiset
pq:	mkbin
	g++ study_priority.cpp -o bin/pq
heap_sort: mkbin
	g++ heap_sort.cpp -o bin/heap_sort
lcs:	mkbin
	g++ -g lcs.cpp -o bin/lcs
min_step:
	g++ -g min_step.cpp -o bin/min_step
bs:
	g++ -g bin_search.cpp -o bin/bs
ne:
	g++ -g nth_element.cpp -o bin/ne
test:
	g++ -g test.cpp -o bin/test
maxRect:	mkbin
	g++ -g maxRect.cpp -o bin/maxRect
bucket_sort:	mkbin
	g++ -g bucket_sort.cpp -o bin/bucket_sort
