mkbin:
	mkdir -p bin
count_smaller:	mkbin
	gcc count_smaller.cpp -o bin/count_smaller
clear:
	rm -rf bin
arithmeticSlices:	mkbin
	g++ arithmeticSlices.cpp -o bin/arithmeticSlices
connectRight117:	mkbin
	g++ connectRight117.cpp -o bin/connectRight117
median:	mkbin
	g++ median.cpp -o bin/median
del_bst: mkbin
	g++ del_node_bst450.cpp -o bin/del_bst
add_bin:	mkbin
	g++ add_bin.cpp -o bin/add_bin
stack_bin:	mkbin
	g++ stack_bin.cpp -o bin/stack_bin
gen_par:	mkbin
	g++ gen_par.cpp -o bin/gen_par
lexord:	mkbin
	g++ -g lexical_ord4.cpp -o bin/lexord
sym_tree:	mkbin
	g++ -g sym_tree.cpp -o bin/sym_tree
max_slide_win:	mkbin
	g++ -g max_slide_window3.cpp -o bin/max_slide_win
ts:	mkbin
	g++ -g three_sum.cpp -o bin/ts
lis: mkbin
	g++ -g lis2.cpp -o bin/lis
dungeon:	mkbin
	g++ -g dungeon3.cpp -o bin/dungeon
coin_change:	mkbin
	g++ -g coin_change.cpp -o bin/coin_change
distance:	mkbin
	g++ -g distance.cpp -o bin/distance
permute:	mkbin
	g++ -g permute.cpp -o bin/permute
rmDigits:	mkbin
	g++ -g rmDigits.cpp -o bin/rmDigits
findIslands:
	g++ -g findIslands.cpp -o bin/findIslands
hindex:
	g++ -g hindex.cpp -o bin/hindex
rangeSum:
	g++ -g rangeSum2.cpp -o bin/rangeSum
graycode:
	g++ -g graycode.cpp -o bin/graycode
ttd:
	g++ -g trackTreeDfs.cpp -o bin/ttd
stock1:	mkbin
	g++ -g stock1.cpp -o bin/stock1
stock2:	mkbin
	g++ -g stock2.cpp -o bin/stock2
stock3:	mkbin
	g++ -g stock3.cpp -o bin/stock3
stock4:	mkbin
	g++ -g stock4.cpp -o bin/stock4
dps:	mkbin
	g++ -g dp_square.cpp -o bin/dps
add_num:	mkbin
	g++ -g additive_num.cpp -o bin/add_num
swm:	mkbin
	g++ -g slide_win_method.cpp -o bin/swm
uglyNumber:	mkbin
	g++ -g uglyNumber.cpp -o bin/uglyNumber
findAnagrams:	mkbin
	g++ -g findStr.cpp -o bin/findAnagrams
countStr:	mkbin
	g++ -g countStr.cpp -o bin/countStr
arrangeCoins: mkbin
	g++ -g arrangeCoins.cpp -o bin/arrangeCoins
single2:	mkbin
	g++ -g single2.cpp -o bin/single2
maxRect:	mkbin
	g++ -g maxRect.cpp -o bin/maxRect
canIWin:	mkbin
	g++ -g canIWin.cpp -o bin/canIWin
wordBreak:	mkbin
	g++ -g wordBreak.cpp -o bin/wordBreak
subset2:	mkbin
	g++ -g subset2.cpp -o bin/subset2
maxXOR:	mkbin
	g++ -g maxXOR.cpp -o bin/maxXOR
findMin:	mkbin
	g++ -g findMin.cpp -o bin/findMin
robTree:	mkbin
	g++ -g robTree.cpp -o bin/robTree
intBreak:	mkbin
	g++ -g intBreak.cpp -o bin/intBreak
checkInclude: mkbin
	g++ -g checkInclude.cpp -o bin/checkInclude
n-queens:	mkbin
	g++ -g n-queens.cpp -o bin/n-queens
cloverRect:	mkbin
	g++ -g cloverRect.cpp -o bin/cloverRect
sudoku:	mkbin
	g++ -g sudoku.cpp -o bin/sudoku
sudoku2:	mkbin
	g++ -g sudoku2.cpp -o bin/sudoku2
beautiArrange:	mkbin
	g++ -g beautiArrange.cpp -o bin/beautiArrange
countPrimes:	mkbin
	g++ -g countPrimes.cpp -o bin/countPrimes
countSmaller:	mkbin
	g++ -g countSmaller.cpp -o bin/countSmaller
countRangeSum:	mkbin
	g++ -g countRangeSum.cpp -o bin/countRangeSum
countSmaller2:	mkbin
	g++ -g countSmaller2.cpp -o bin/countSmaller2
findSubString:	mkbin
	g++ -g findSubString.cpp -o bin/findSubString
findSubString2:	mkbin
	g++ -g findSubString2.cpp -o bin/findSubString2
validPreOrder:	mkbin
	g++ -g validPreOrder.cpp -o bin/validPreOrder
validPreOrder2:	mkbin
	g++ -g validPreOrder2.cpp -o bin/validPreOrder2
maxRepeat:	mkbin
	g++ -g maxRepeat.cpp -o bin/maxRepeat
buildTree:	mkbin
	g++ -g buildTree.cpp -o bin/buildTree
boardExist:	mkbin
	g++ -g boardExist.cpp -o bin/boardExist
addOps:	mkbin
	g++ -g addOps.cpp -o bin/addOps
sortPair:	mkbin
	g++ -g sortPair.cpp -o bin/sortPair
trap:	mkbin
	g++ -g trap.cpp -o bin/trap
trap2:	mkbin
	g++ -g trap2.cpp -o bin/trap2
numTrees: 	mkbin
	g++ -g numTrees.cpp -o bin/numTrees
kthSmallest: mkbin
	g++ -g getKFromSortM.cpp -o bin/kthSmallest
treeZigzag:	mkbin
	g++ -g treeZigzag.cpp -o bin/treeZigzag
lru:	mkbin
	g++ -g lru.cpp -o bin/lru
numDecode:	mkbin
	g++ -g numDecode.cpp -o bin/numDecode
jump:	mkbin
	g++ -g jumpDist.cpp -o bin/jump
interleave:	mkbin
	g++ -g interleave.cpp -o bin/interleave
combine:	mkbin
	g++ -g combine.cpp -o bin/combine
subarraySum:	mkbin
	g++ -g subarraySum.cpp -o bin/subarraySum